export const TOPIC_LIST_REQUEST = "TOPIC_LIST_REQUEST";
export const TOPIC_LIST_SUCCESS = "TOPIC_LIST_SUCCESS";
export const TOPIC_LIST_FAIL = "TOPIC_LIST_FAIL";

export const TOPIC_DETAILS_REQUEST = "TOPIC_DETAILS_REQUEST";
export const TOPIC_DETAILS_SUCCESS = "TOPIC_DETAILS_SUCCESS";
export const TOPIC_DETAILS_FAIL = "TOPIC_DETAILS_FAIL";
