export const RESOURCE_LIST_REQUEST = "RESOURCE_LIST_REQUEST";
export const RESOURCE_LIST_SUCCESS = "RESOURCE_LIST_SUCCESS";
export const RESOURCE_LIST_FAIL = "RESOURCE_LIST_FAIL";

export const RESOURCE_DETAILS_REQUEST = "RESOURCE_DETAILS_REQUEST";
export const RESOURCE_DETAILS_SUCCESS = "RESOURCE_DETAILS_SUCCESS";
export const RESOURCE_DETAILS_FAIL = "RESOURCE_DETAILS_FAIL";
